// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXrIKEqvolJYMIa4sSfwsBXcU9FD0MTvw',
    appId: '1:723323187687:web:94843b528c583e13d78d42',
    messagingSenderId: '723323187687',
    projectId: 'firebase-auth-3011',
    authDomain: 'fir-auth-3011.firebaseapp.com',
    storageBucket: 'firebase-auth-3011.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8D2RvI093WOGI9OUWPeW4gN20CgyfrBU',
    appId: '1:723323187687:android:ff67e1256c00ed04d78d42',
    messagingSenderId: '723323187687',
    projectId: 'firebase-auth-3011',
    storageBucket: 'firebase-auth-3011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9koo1zJU-mR_gBsPFNAQHqrE6QTRZkwI',
    appId: '1:723323187687:ios:5a192d4fa15b3307d78d42',
    messagingSenderId: '723323187687',
    projectId: 'firebase-auth-3011',
    storageBucket: 'firebase-auth-3011.firebasestorage.app',
    iosBundleId: 'com.example.neocaretry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9koo1zJU-mR_gBsPFNAQHqrE6QTRZkwI',
    appId: '1:723323187687:ios:5a192d4fa15b3307d78d42',
    messagingSenderId: '723323187687',
    projectId: 'firebase-auth-3011',
    storageBucket: 'firebase-auth-3011.firebasestorage.app',
    iosBundleId: 'com.example.neocaretry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXrIKEqvolJYMIa4sSfwsBXcU9FD0MTvw',
    appId: '1:723323187687:web:21a6277d757c5839d78d42',
    messagingSenderId: '723323187687',
    projectId: 'firebase-auth-3011',
    authDomain: 'fir-auth-3011.firebaseapp.com',
    storageBucket: 'firebase-auth-3011.firebasestorage.app',
  );
}
